### PR TITLE
feat: add fmt capabilities

### LINKED ISSUE #44: File formatting
It's common for a LSP to integrate file formatting, Dagger LSP should not be an exception.

When user press command to format file, Dagger LSP should execute `cue fmt` function and returns the formatted file.

### PR DESCRIPTION
**Pull request by b4nst**
An attempt at including formatting to the LSP. I'm quite new to LSP implementation, not sure if there's a standard for passing options to the formatter. I'll dig a bit in the doc later see if I find something useful.

Resolves #44

### CODE REVIEW

**Comment by b4nst** [comment]
Went a bit too fast on this one. I need to get the file from the workspace and not a dumb `os.ReadFile`, otherwise it doesn't take current changes into account 🤦 .

**Comment by TomChv** [comment]
Hey, thanks for your time and contribution :rocket:

> Went a bit too fast on this one. I need to get the file from the workspace and not a dumb os.ReadFile, otherwise it doesn't take current changes into account 🤦 .

Actually I think it's ok to keep the same logic as [`cue fmt`](https://github.com/cue-lang/cue/blob/master/cmd/cue/cmd/fmt.go) and format the full file.
That's maybe a simpler implementation for now?

**Comment by b4nst** [comment]
I don't see any issue formatting the whole file. However when doing some tests, it seems the `os.ReadFile` is happening before the file is actually saved. I guess that's the normal flow of an `on save` hook: hit save => triggers hooks => actually save with the modified file.
Meaning I ended up overriding my changes with the last state saved in file. It's also maybe an issue with the lsp client (I'm using Helix editor embedded client) that should send the current buffer instead of the local path. Not sure of the right client implementation for this feature.

**Review by grouville — CHANGES_REQUESTED** [review]
I've tested locally, and it seems that it overrides the local changes, prior saving. A solution would be to maybe move that function to the `onsave` handler, or find a way to update before that (doing a reload of the plan)

**Comment by b4nst** [comment]
I wonder if we should start implementing `documentDidChange` and reload the plan with changes. And then use the plan itself to somehow get the file content, or the `ast.Node` to feed it to `format.Source` or `format.Node`.
I'm just a bit concerned by the performances of a plan reload with every changes.

**Comment by b4nst** [comment]
I ran some quick and dirty stuff [here](https://github.com/b4nst/cuelsp/tree/sandbox/try-with-did-change-update), using a simple `sync.Map` as a storage. And it does work.

So I guess updating the Plan and getting back the file directly from it should solve our issue. I'll explore a way to do so

**Comment by b4nst** [comment]
@grouville I updated my code to take the file directly from the plan and add an override system to the plan. It seems to work well but it feels kinda hacky tbh.
I'm wonderning if we shouldn't be better using the Overlay capabilities of [load.Config](https://pkg.go.dev/cuelang.org/go@v0.4.3/cue/load#Config)

**Comment by TomChv** [comment]
I'll take some time today to check your solution too

**Comment by b4nst** [comment]
Huum, maybe because the file didn't build correctly it was not in the list of files of the main Plan. I honestly have to give a better try to this one. It requires more work than this sort of hack

**Pull request closed without merging**
