### PR TITLE
Rename daggerlsp to cuelsp

### PR DESCRIPTION
**Pull request by shykes**
This PR includes all necessary changes for renaming this project to *cuelsp*.

### CODE REVIEW

**Comment by TomChv** [comment]
Can your rebase your PR, #73 creates conflict with your

**Comment by shykes** [comment]
Rebasing now.

**Comment by shykes** [comment]
All done on my end, handing off to you @grouville

**Comment by grouville** [comment]
Tested locally. Cuelsp as a standalone works fine

**Pull request merged**
